### ISSUE TITLE
Cannot find a distribution for ZopeUndo 4.3

### ISSUE THREAD

**Issue by thet** [zopefoundation/ZopeUndo#2]
While installing Plone buildout.coredev 5.1 I get the following error:

```
Getting distribution for 'ZopeUndo==4.3'.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
  Getting distribution for 'ZopeUndo==4.3'.
Error: Couldn't find a distribution for 'ZopeUndo==4.3'
```

Pinning to ``ZopeUndo = 4.2`` solves the problem.

ZopeUndo 4.3 is only available as a tar.gz package, but I don't see a problem with that: https://pypi.python.org/pypi/ZopeUndo

ZopeUndo 4.2 is also available as wheel: https://pypi.python.org/pypi/ZopeUndo/4.2

**Comment by thet** [comment]
Strangely, I also get the following error:

```
Installing releaser.
Getting distribution for 'wheel==0.30.0'.
While:
  Installing releaser.
  Getting distribution for 'wheel==0.30.0'.
Error: Couldn't find a distribution for 'wheel==0.30.0'.
```

Fixed by ``wheel = 0.29.0``.

**Comment by hannosch** [comment]
I can't reproduce this with a minimal buildout.cfg:
```
[buildout]
parts = undo
versions = versions

[versions]
ZopeUndo = 4.3

[undo]
recipe = zc.recipe.egg
eggs = ZopeUndo
```

This seems to work fine. Looking at https://pypi.python.org/simple/wheel/ - there are tar.gz files for both wheel 0.29 and 0.30.

I don't know what this could be, but would guess either something in your local caches, or some too new / broken version of setuptools.

**Comment by thet** [comment]
You're right. After an OS upgrade I didn't delete the ~/.buildout directory contents. After I did and all eggs were downloaded freshly, it worked.

Sorry for the noise :)
